### ISSUE TITLE
Out of Memory issue with MemoryMode config

### ISSUE THREAD

**Issue by dev8500** [eneim/kohii#110]
Hi,

I am seeing an out of memory issue on Android 7 device when using memory mode setting. As per docs, it says the memory mode can make sure such errors don't occur. Not sure if this is a bug in the memory mode code. Plz investigate.

**This is my Kohii code:**
```Java
Kohii kohii = Kohii.get(context);
        kohii.register(fragment, MemoryMode.NORMAL).addBucket(view);
        kohii.setUp(Uri.parse(linkedVideos.get(i).video_url), options -> {
            options.setPreload(true);
            return null;
        })
                .bind(playerView, null);
```

**Error**:
```
2020-10-10 17:19:05.416 21941-22322/com.rollup E/ExoPlayerImplInternal: Source error.
    com.google.android.exoplayer2.upstream.Loader$UnexpectedLoaderException: Unexpected OutOfMemoryError: Failed to allocate a 82 byte allocation with 3880 free bytes and 3KB until OOM
        at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:411)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
        at java.lang.Thread.run(Thread.java:761)
     Caused by: java.lang.OutOfMemoryError: Failed to allocate a 82 byte allocation with 3880 free bytes and 3KB until OOM
        at java.lang.StringFactory.newStringFromBytes(StringFactory.java:79)
        at com.android.okhttp.okio.Buffer.readString(Buffer.java:582)
        at com.android.okhttp.okio.Buffer.readUtf8(Buffer.java:557)
        at com.android.okhttp.okio.Buffer.readUtf8Line(Buffer.java:618)
        at com.android.okhttp.okio.RealBufferedSource.readUtf8LineStrict(RealBufferedSource.java:203)
        at com.android.okhttp.internal.http.HttpConnection.readHeaders(HttpConnection.java:220)
        at com.android.okhttp.internal.http.HttpConnection.readResponse(HttpConnection.java:199)
        at com.android.okhttp.internal.http.HttpTransport.readResponseHeaders(HttpTransport.java:80)
        at com.android.okhttp.internal.http.HttpEngine.readNetworkResponse(HttpEngine.java:942)
        at com.android.okhttp.internal.http.HttpEngine.readResponse(HttpEngine.java:818)
        at com.android.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:480)
        at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getResponse(HttpURLConnectionImpl.java:422)
        at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getResponseCode(HttpURLConnectionImpl.java:538)
        at com.android.okhttp.internal.huc.DelegatingHttpsURLConnection.getResponseCode(DelegatingHttpsURLConnection.java:105)
        at com.android.okhttp.internal.huc.HttpsURLConnectionImpl.getResponseCode(HttpsURLConnectionImpl.java)
        at com.google.android.exoplayer2.upstream.DefaultHttpDataSource.open(DefaultHttpDataSource.java:294)
        at com.google.android.exoplayer2.upstream.DefaultDataSource.open(DefaultDataSource.java:257)
        at com.google.android.exoplayer2.upstream.cache.CacheDataSource.openNextSource(CacheDataSource.java:455)
        at com.google.android.exoplayer2.upstream.cache.CacheDataSource.open(CacheDataSource.java:284)
        at com.google.android.exoplayer2.upstream.StatsDataSource.open(StatsDataSource.java:83)
        at com.google.android.exoplayer2.source.ProgressiveMediaPeriod$ExtractingLoadable.load(ProgressiveMediaPeriod.java:934)
        at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:381)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607) 
        at java.lang.Thread.run(Thread.java:761) 
```

**Comment by eneim** [comment]
@dev8500 Can you share the Video url you used in this case? It maybe that the amount of memory to play the Video is out of handlable range. But will take a look.

**Comment by eneim** [comment]
@dev8500 Will have a fix to match it with the spec. Though it turns out that the `onTrimMemory` callback is called when your App is in the background, so Kohii will try to use the latest available level.
