### ISSUE TITLE
I get an error when I quickly scroll up and down with Recyclerview

### ISSUE THREAD

**Issue by serkanucar** [eneim/kohii#122]
https://github.com/eneim/kohii/blob/4ee0d39e848fc1e361cdbd0085e37de5818969ff/kohii-core/src/main/java/androidx/recyclerview/widget/RecyclerViewUtils.kt#L39

``` 
FATAL EXCEPTION: main
    Process: com.myapplication, PID: 16263
    java.lang.IllegalStateException: parent must not be null
        at androidx.recyclerview.widget.RecyclerViewUtils.fetchItemViewParams(**RecyclerViewUtils.kt:39**)
        at androidx.recyclerview.widget.RecyclerViewUtils.fetchViewHolder(RecyclerViewUtils.kt:45)
        at kohii.v1.internal.RecyclerViewBucket.onChildViewAttachedToWindow(RecyclerViewBucket.kt:107)
        at androidx.recyclerview.widget.RecyclerView.dispatchChildAttached(RecyclerView.java:7561)
        at androidx.recyclerview.widget.RecyclerView$5.addView(RecyclerView.java:860)
        at androidx.recyclerview.widget.ChildHelper.addView(ChildHelper.java:107)
        at androidx.recyclerview.widget.RecyclerView$LayoutManager.addViewInt(RecyclerView.java:8601)
        at androidx.recyclerview.widget.RecyclerView$LayoutManager.addView(RecyclerView.java:8559)
        at androidx.recyclerview.widget.RecyclerView$LayoutManager.addView(RecyclerView.java:8547)
        at androidx.recyclerview.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1641)
        at androidx.recyclerview.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1587)
        at androidx.recyclerview.widget.LinearLayoutManager.scrollBy(LinearLayoutManager.java:1391)
        at androidx.recyclerview.widget.LinearLayoutManager.scrollVerticallyBy(LinearLayoutManager.java:1128)
        at androidx.recyclerview.widget.RecyclerView.scrollStep(RecyclerView.java:1841)
        at androidx.recyclerview.widget.RecyclerView$ViewFlinger.run(RecyclerView.java:5302)
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:996)
        at android.view.Choreographer.doCallbacks(Choreographer.java:794)
        at android.view.Choreographer.doFrame(Choreographer.java:725)
        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:981)
        at android.os.Handler.handleCallback(Handler.java:883)
        at android.os.Handler.dispatchMessage(Handler.java:100)
        at android.os.Looper.loop(Looper.java:237)
        at android.app.ActivityThread.main(ActivityThread.java:7814)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1075)
```

**Comment by eneim** [comment]
Thanks. It is a bug, it will be fixed in the next update.

**Comment by serkanucar** [comment]
When is the next update?

**Comment by eneim** [comment]
@serkanucar 1.2.0 is released.
