### ISSUE TITLE
NoSuchMethodError: No virtual method setPlayClearSamplesWithoutKeys

### ISSUE THREAD

**Issue by developer--** [eneim/kohii#135]
I have picked up example codes from your Tiktok repo and I'm getting that runtime crash
```
Kohii: 1.1.1.2011003
exoplayer: 2.12.3
```
```
java.lang.NoSuchMethodError: No virtual method setPlayClearSamplesWithoutKeys(Z)Lcom/google/android/exoplayer2/DefaultRenderersFactory; in class Lcom/google/android/exoplayer2/DefaultRenderersFactory; or its super classes (declaration of 'com.google.android.exoplayer2.DefaultRenderersFactory' appears in /data/app/~~3BTPlbq706uJRejVnPpBng==/com.mrkt.shopper-ZyITPNZMU-BHJQJYAghuhw==/base.apk!classes3.dex)
        at kohii.v1.exoplayer.KohiiKt$createKohii$bridgeCreatorFactory$1.invoke(Kohii.kt:137)
        at kohii.v1.exoplayer.KohiiKt$createKohii$bridgeCreatorFactory$1.invoke(Unknown Source:2)
        at kohii.v1.exoplayer.PlayerViewPlayableCreator$bridgeCreator$1.invoke(PlayerViewPlayableCreator.kt:65)
        at kohii.v1.exoplayer.PlayerViewPlayableCreator$bridgeCreator$1.invoke(PlayerViewPlayableCreator.kt:37)
        at kotlin.UnsafeLazyImpl.getValue(Lazy.kt:81)
        at kohii.v1.exoplayer.PlayerViewPlayableCreator.createPlayable(PlayerViewPlayableCreator.kt:76)
        at kohii.v1.core.Binder.providePlayable(Binder.kt:94)
        at kohii.v1.core.Binder.bind(Binder.kt:65)
        at kohii.v1.core.Binder.bind$default(Binder.kt:62)
```

**Comment by eneim** [comment]
@developer-- ExoPlayer 2.12.3 is not compatible with this version of Kohii. Please use 2.11.3.

**Comment by developer--** [comment]
@eneim Ok thanks, will try

**Comment by developer--** [comment]
Downgraded and now it throws that exception:
```
 java.lang.IllegalArgumentException: No Manager and Bucket available for com.google.android.exoplayer2.ui.PlayerView{92a639 V.E...... ........ 0,0-1412,2956 #7f0a0782 app:id/videoSurfaceView}
        at kohii.v1.core.Master$BindRequest.onBind$kohii_core_release(Master.kt:764)
        at kohii.v1.core.Master$Dispatcher$1.handleMessage(Master.kt:107)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:223)
        at android.app.ActivityThread.main(ActivityThread.java:7660)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
```

that is my setup
```
kohii.setUp(product.videoUrl) {
          tag = "${product.videoUrl}+${adapterPosition}"
          preload = true
          repeatMode = Common.REPEAT_MODE_ONE
          controller = object : Playback.Controller {
            override fun kohiiCanStart(): Boolean = true
            override fun kohiiCanPause(): Boolean = true
            override fun setupRenderer(playback: Playback, renderer: Any?) {
              playerContainer.setOnClickListener {
                val playable = playback.playable ?: return@setOnClickListener
                if (playable.isPlaying()) {
                  playback.manager.pause(playable)
                } else {
                  playback.manager.play(playable)
                }
              }
            }

            override fun teardownRenderer(playback: Playback, renderer: Any?) {
              playerContainer.setOnClickListener(null)
            }
          }
        }.bind(playerView)
```
