### ISSUE TITLE
E/Kohii::Bridge: Error: com.google.android.exoplayer2.source.UnrecognizedInputFormatException

### ISSUE THREAD

**Issue by developer--** [eneim/kohii#136]
Here is my provider
```
object KohiiProvider {

  private val capsule: Capsule<Kohii, Pair<Context, MediaSourceFactory>> =
    Capsule(creator = { (context, factory) ->
      createKohii(context, mediaSourceFactoryCreator = { factory })
    })

  private fun get(context: Context, factory: MediaSourceFactory) = capsule.get(context to factory)

  operator fun get(context: Context) = get(context, /* Your custom MediaSourceFactory */ ProgressiveMediaSource.Factory {
    create(context)
  })

  private fun create(context: Context) : DataSource{
    val userAgent = Util.getUserAgent(context,context.applicationInfo.name)
    val dataSourceFactory: DataSource.Factory = DefaultHttpDataSourceFactory(userAgent,null,
      DefaultHttpDataSource.DEFAULT_CONNECT_TIMEOUT_MILLIS,
      DefaultHttpDataSource.DEFAULT_READ_TIMEOUT_MILLIS,
      true)
    return dataSourceFactory.createDataSource()
  }

}
```
inside adapter 
```
kohii.setUp(product.videoUrl) {
          tag = "${product.videoUrl}+${adapterPosition}"
          preload = true
          repeatMode = Common.REPEAT_MODE_ONE
          controller = object : Playback.Controller {
            override fun kohiiCanStart(): Boolean = true
            override fun kohiiCanPause(): Boolean = true
            override fun setupRenderer(playback: Playback, renderer: Any?) {
              playerContainer.setOnClickListener {
                val playable = playback.playable ?: return@setOnClickListener
                if (playable.isPlaying()) {
                  playback.manager.pause(playable)
                } else {
                  playback.manager.play(playable)
                }
              }
            }

            override fun teardownRenderer(playback: Playback, renderer: Any?) {
              playerContainer.setOnClickListener(null)
            }
          }
        }.bind(playerView)
```

Full log
```
 com.google.android.exoplayer2.source.UnrecognizedInputFormatException: None of the available extractors (MatroskaExtractor, FragmentedMp4Extractor, Mp4Extractor, Mp3Extractor, AdtsExtractor, Ac3Extractor, TsExtractor, FlvExtractor, OggExtractor, PsExtractor, WavExtractor, AmrExtractor, Ac4Extractor, FlacExtractor) could read the stream.
        at com.google.android.exoplayer2.source.ProgressiveMediaPeriod$ExtractorHolder.selectExtractor(ProgressiveMediaPeriod.java:1090)
        at com.google.android.exoplayer2.source.ProgressiveMediaPeriod$ExtractingLoadable.load(ProgressiveMediaPeriod.java:969)
        at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:391)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:923)
```

Any idea what is the problem? cause without your library exoplayer can play that videos.
all videos are **hls** formated videos

**Comment by eneim** [comment]
@developer-- Your video is an *HLS* but your MediaSourceFactory is `ProgressiveMediaSource.Factory`:

```
/* Your custom MediaSourceFactory */ ProgressiveMediaSource.Factory {
    create(context)
  }
```

**Comment by developer--** [comment]
Oh write 
```
  operator fun get(context: Context) =
    get(context, HlsMediaSource.Factory(create(context)))
```
