### ISSUE TITLE
Issue with HLS playback

### ISSUE THREAD

**Issue by dinesh1301** [eneim/kohii#140]
I tried playing hls videos using kohii and exoplayer, found the following error. After researching I found that this bug was fixed in latest version(2.12.x) of exoplayer  however currently kohii does not support 2.12.x. Is there a way out of this? Is it possible to support (2.12.x) exoplayer or find a possible fix for this issue.

```2021-02-09 16:11:06.420 19581-22026/com.bettyapp.betty E/ExoPlayerImplInternal: Source error
      com.google.android.exoplayer2.ParserException: Loading finished before preparation is complete.
        at com.google.android.exoplayer2.source.hls.HlsSampleStreamWrapper.maybeThrowPrepareError(HlsSampleStreamWrapper.java:260)
        at com.google.android.exoplayer2.source.hls.HlsMediaPeriod.maybeThrowPrepareError(HlsMediaPeriod.java:164)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:619)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:329)
        at android.os.Handler.dispatchMessage(Handler.java:103)
        at android.os.Looper.loop(Looper.java:214)
        at android.os.HandlerThread.run(HandlerThread.java:67)```

**Comment by eneim** [comment]
@dinesh1301 The latest Kohii version is compatible with 2.11.8. 2.12.x is not supported yet. I plan to wait and go to support 2.13.x directly. Please use the 2.11.8 dependency for your app for now.

**Comment by adityapatadia** [comment]
@eneim we have found out that the issue happens when there is HLS stream which uses byte-range. Is there a bug in kohii or exoplayer related to this?

**Comment by adityapatadia** [comment]
We are really stuck here. I would appreciate if we can get some resolution here.

**Comment by adityapatadia** [comment]
Also 2.13.x is released so would be great to see kohii updated to support that. It might solve this issue.

**Comment by adityapatadia** [comment]
Also 2.13.x is released so would be great to see kohii updated to support that. It might solve this issue.
