### ISSUE TITLE
Kohii crash when use exoplayer 2.13.3 NoClassDefFoundError TrackSelection

### ISSUE THREAD

**Issue by ahmadrushdie** [eneim/kohii#179]
dependancies 

 def kohii_version = "1.1.0.2011003"
    implementation "im.ene.kohii:kohii-core:${kohii_version}"
    implementation "im.ene.kohii:kohii-exoplayer:${kohii_version}"
    implementation "com.google.android.exoplayer:exoplayer:2.13.3"

 java.lang.NoClassDefFoundError: Failed resolution of: Lcom/google/android/exoplayer2/trackselection/TrackSelection$Factory;
        at kohii.v1.exoplayer.ExoPlayerConfig.<init>(ExoPlayerConfig.kt:45)
        at kohii.v1.exoplayer.ExoPlayerConfig.<clinit>(ExoPlayerConfig.kt:76)
        at kohii.v1.exoplayer.DefaultExoPlayerProvider.<init>(DefaultExoPlayerProvider.kt:32)
        at kohii.v1.exoplayer.PlayerViewPlayableCreator$Companion$defaultBridgeCreatorFactory$1.invoke(PlayerViewPlayableCreator.kt:52)
        at kohii.v1.exoplayer.PlayerViewPlayableCreator$Companion$defaultBridgeCreatorFactory$1.invoke(PlayerViewPlayableCreator.kt:44)
        at kohii.v1.exoplayer.PlayerViewPlayableCreator$bridgeCreator$1.invoke(PlayerViewPlayableCreator.kt:65)
        at kohii.v1.exoplayer.PlayerViewPlayableCreator$bridgeCreator$1.invoke(PlayerViewPlayableCreator.kt:37)
        at kotlin.UnsafeLazyImpl.getValue(Lazy.kt:81)
        at kohii.v1.exoplayer.PlayerViewPlayableCreator.createPlayable(PlayerViewPlayableCreator.kt:76)
        at kohii.v1.core.Binder.providePlayable(Binder.kt:94)
        at kohii.v1.core.Binder.bind(Binder.kt:65)

**Comment by haris15** [comment]
Same issue i am facing do you find any solution @ahmadrushdie ?

**Comment by eneim** [comment]
Each Kohii library has an supported ExoPlayer version. Using other ExoPlayer version may not work well and it can produce crash like this. Please make sure to use the same ExoPlayer verion as mentioned in the kohii version.

For example: 1.2.0.201108 -> ExoPlayer 2.11.8 (the number 201108 is taken from the ExoPlayer's library version number).
