### ISSUE TITLE
Change video uri when rotate screen

### ISSUE THREAD

**Issue by Diegofr104** [eneim/kohii#69]
I want to know if i can change a video uri when the screen rotate(one uri in landscape and another in portrait), i try to bind again the player and show me an error: 

```
java.lang.IllegalArgumentException: Failed requirement.
        at kohii.v1.core.Binder.providePlayable(Binder.kt:72)
        at kohii.v1.core.Binder.bind(Binder.kt:52)
        at com.goodtest.utils.StaggeredRecyclerViewAdapterHomeMemorySlider$15$1.onPaused(StaggeredRecyclerViewAdapterHomeMemorySlider.java:2562)
        at kohii.v1.core.Playback.onPlayerStateChanged(Playback.kt:400)
        at kohii.v1.core.PlayerEventListeners.onPlayerStateChanged(Interfaces.kt:118)
        at com.google.android.exoplayer2.ExoPlayerImpl.lambda$setPlayWhenReady$0(ExoPlayerImpl.java:254)
        at com.google.android.exoplayer2.-$$Lambda$ExoPlayerImpl$OKMPvkXpqXeKaJZFBZ8m9YfNXpE.invokeListener(Unknown Source:4)
        at com.google.android.exoplayer2.BasePlayer$ListenerHolder.invoke(BasePlayer.java:165)
        at com.google.android.exoplayer2.ExoPlayerImpl.invokeAll(ExoPlayerImpl.java:825)
        at com.google.android.exoplayer2.ExoPlayerImpl.lambda$notifyListeners$6(ExoPlayerImpl.java:718)
        at com.google.android.exoplayer2.-$$Lambda$ExoPlayerImpl$DrcaME6RvvSdC72wmoYPUB4uP5w.run(Unknown Source:4)
        at com.google.android.exoplayer2.ExoPlayerImpl.notifyListeners(ExoPlayerImpl.java:728)
        at com.google.android.exoplayer2.ExoPlayerImpl.notifyListeners(ExoPlayerImpl.java:718)
        at com.google.android.exoplayer2.ExoPlayerImpl.setPlayWhenReady(ExoPlayerImpl.java:254)
        at com.google.android.exoplayer2.SimpleExoPlayer.updatePlayWhenReady(SimpleExoPlayer.java:1224)
        at com.google.android.exoplayer2.SimpleExoPlayer.setPlayWhenReady(SimpleExoPlayer.java:921)
        at kohii.v1.exoplayer.PlayerViewBridge.pause(PlayerViewBridge.kt:160)
        at kohii.v1.core.AbstractPlayable.onPause(AbstractPlayable.kt:81)
        at kohii.v1.internal.PlayableDispatcher.justPause(PlayableDispatcher.kt:136)
        at kohii.v1.internal.PlayableDispatcher.pause$kohii_core_release(PlayableDispatcher.kt:109)
        at kohii.v1.core.Group.refresh(Group.kt:171)
        at kohii.v1.core.Group.handleMessage(Group.kt:50)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6680)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
```

There is a method or something i can do in kohii to do that?

**Comment by eneim** [comment]
You want to use 2 different Videos in different orientation for the same position? What is the difference between videos?

**Comment by Diegofr104** [comment]
Yes i want 2 different videos for the same position and change that video if you are in landscape or portrait. the difference is that the portrait video has a 2 videos running in one(mp4 video encoded like this), one that covers all the screen with a blur radius, then another video on top of previous one with smaller width and height.(uploaded a screenshot if how it looks...[https://i.imgur.com/uzVEJXo.png](https://i.imgur.com/uzVEJXo.png) )
In the landscape video is the same video but without blur.

**Comment by alphater** [comment]
> 您想在同一位置使用不同方向的 2 个不同视频吗？视频之间有什么区别？

Pls is there any update on this issue?
